services:
  app:
    build:
      context: ./satusehat-kyc
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - IHS_CLIENT_SECRET=${IHS_CLIENT_SECRET}
      - IHS_SECRET_KEY=${IHS_SECRET_KEY}
      - PIN=${PIN}
      - ORIGIN=${ORIGIN}
      - HOST=0.0.0.0
      - PORT=3000
    expose:
      - "3000"
